### ISSUE TITLE
Faile to connect, secondary seems unresponsive

### ISSUE THREAD

**Issue by jfdzar** [b2un0/silabs-multipan-docker#1]
Hi,
as I am running Home-Assistant in Docker container I found this repository as a solution to use the Sonoff Dongle-E as RCP

I created the docker compose as especified in the description, but when I start I get the following log.
I get the error described in the last two lines then forever and the server is not available

Any ideas?

multipan    | WARNING in function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
multipan    | [16:48:56:464782] Info : [CPCd v4.3.1.0] [Library API v3] [RCP Protocol v4]
multipan    | [16:48:56:464812] Info : Git commit: 133b29678b3d0bc7578e098d2f46b4d5bcd2ebb4 / branch: 
multipan    | [16:48:56:464818] Info : Sources hash: ff8300587e7e4ab1def7a89a272c0baef32f9eb3bff9b0ba06b94e655d652367
multipan    | [16:48:56:464823] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
multipan    | [16:48:56:464849] Info : Reading cli arguments
multipan    | [16:48:56:464855] Info : /usr/local/bin/cpcd 
multipan    | [16:48:56:465483] Info : Reading configuration
multipan    | [16:48:56:465490] Info :   file_path = /usr/local/etc/cpcd.conf
multipan    | [16:48:56:465494] Info :   instance_name = cpcd_0
multipan    | [16:48:56:465497] Info :   socket_folder = /dev/shm
multipan    | [16:48:56:465501] Info :   operation_mode = MODE_NORMAL
multipan    | [16:48:56:465504] Info :   use_encryption = false
multipan    | [16:48:56:465507] Info :   binding_key_file = /root/.cpcd/binding.key
multipan    | [16:48:56:465511] Info :   stdout_tracing = false
multipan    | [16:48:56:465514] Info :   file_tracing = false
multipan    | [16:48:56:465517] Info :   lttng_tracing = false
multipan    | [16:48:56:465520] Info :   enable_frame_trace = false
multipan    | [16:48:56:465524] Info :   traces_folder = /dev/shm/cpcd-traces
multipan    | [16:48:56:465527] Info :   bus = UART
multipan    | [16:48:56:465530] Info :   uart_baudrate = 460800
multipan    | [16:48:56:465534] Info :   uart_hardflow = true
multipan    | [16:48:56:465537] Info :   uart_file = /dev/ttyACM0
multipan    | [16:48:56:465540] Info :   fu_recovery_pins_enabled = false
multipan    | [16:48:56:465543] Info :   fu_connect_to_bootloader = false
multipan    | [16:48:56:465547] Info :   fu_enter_bootloader = false
multipan    | [16:48:56:465550] Info :   restart_cpcd = false
multipan    | [16:48:56:465553] Info :   application_version_validation = false
multipan    | [16:48:56:465557] Info :   print_secondary_versions_and_exit = false
multipan    | [16:48:56:465560] Info :   use_noop_keep_alive = false
multipan    | [16:48:56:465563] Info :   reset_sequence = true
multipan    | [16:48:56:465567] Info :   stats_interval = 0
multipan    | [16:48:56:465570] Info :   rlimit_nofile = 2000
multipan    | [16:48:56:465573] Info : ENCRYPTION IS DISABLED 
multipan    | [16:48:56:465577] Info : Starting daemon in normal mode
multipan    | [16:48:56:476464] Info : Connecting to Secondary...
multipan    | [16:48:58:476687] Info : Failed to connect, secondary seems unresponsive
multipan    | [16:48:58:476713] Info : Connecting to Secondary...

**Comment by Vertikar** [comment]
Just downloaded it today and getting the same thing.

**Comment by Vertikar** [comment]
I updated to the latest firmware - https://github.com/NabuCasa/silabs-firmware/blob/main/RCPMultiPAN/beta/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
And that got it running for me

**Comment by johnappletree** [comment]
I have the same issue @jfdzar mentioned above. i have the skyconnect usb dongle. I tried to flash the new firmware but i fail a this error message: 

`2023-10-17T20:46:00.894955447Z Error: '/data/firmware/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl' does not appear to be a valid GBL image: ValidationError('Image is truncated: tag value is cut off')

2023-10-17T20:46:00.929952425Z s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1

2023-10-17T20:46:00.931043400Z /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.`

**Comment by johnappletree** [comment]
I found my mistake. My firmware download was not correct, therefore flashing failed. In the end it worked using: https://skyconnect.home-assistant.io/
