### ISSUE TITLE
Question: add network device SLZB-06M (zigbee2lan, EFR32MG2

### ISSUE THREAD

**Issue by fir3drag0n** [b2un0/silabs-multipan-docker#14]
There is also the SLZB-06M (zigbee2lan, EFR32MG2 ) available which will soon get matter and multipan support (https://smlight.tech/product/slzb-06/)

Will I also be able to add a network device under "DEVICE"?

**Comment by b2un0** [comment]
> I do not provide any support for the software running in this container.

🤷
